# Generated by Django 5.0.6 on 2024-06-12 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otaku', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='volumen',
        ),
    ]
