# Generated by Django 5.0.6 on 2024-06-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otaku', '0002_remove_manga_precio_remove_manga_volumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manga',
            name='volumen',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
