# Generated by Django 5.0.6 on 2024-06-12 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otaku', '0003_manga_precio_manga_volumen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='editorial',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Editorial',
        ),
        migrations.DeleteModel(
            name='Manga',
        ),
    ]
