# Generated by Django 5.0.6 on 2024-06-12 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otaku', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manga',
        ),
    ]
