# Generated by Django 5.0.6 on 2024-06-12 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otaku', '0006_delete_manga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('portada', models.ImageField(upload_to='images/')),
                ('nombre', models.CharField(max_length=200)),
                ('volumen', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otaku.autor')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otaku.editorial')),
            ],
        ),
    ]
