# Generated by Django 5.0.6 on 2024-06-12 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otaku', '0014_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
