# Generated by Django 5.0.6 on 2024-06-12 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otaku', '0015_delete_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manga',
        ),
    ]
