# Generated by Django 5.0.6 on 2024-06-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otaku', '0017_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
