# Generated by Django 5.0.6 on 2024-06-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otaku', '0018_manga_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='link',
        ),
    ]
