# Generated by Django 5.0.6 on 2024-07-03 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otaku', '0023_itemusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='itemUsuario',
        ),
    ]
