# Generated by Django 5.0.6 on 2024-07-03 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otaku', '0026_carrito_itemcarrito_delete_itemusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otaku.manga')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otaku.factura')),
            ],
        ),
    ]
