# Generated by Django 5.0.6 on 2024-07-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otaku', '0029_boleta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boleta',
        ),
    ]
