# Generated by Django 5.0.6 on 2024-07-03 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otaku', '0030_delete_boleta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('fecha_compra', models.DateField(auto_now_add=True)),
                ('total_carrito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
